required = [
  "github.com/golangci/golangci-lint/cmd/golangci-lint",
]

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "github.com/golang/protobuf"
    non-go = false
