#!/bin/sh

set -e
ROOTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$ROOTPATH"

GOBIN="$ROOTPATH/bin" go install ./vendor/github.com/golang/protobuf/protoc-gen-go
GOBIN="$ROOTPATH/bin" go install ./vendor/github.com/golang/mock/mockgen

test $# -gt 0 || set -- ./...

PATH="$ROOTPATH/bin:$PATH" go generate $@
go fix ./...
