required = [
  "github.com/golangci/golangci-lint/cmd/golangci-lint",
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/golang/mock/mockgen",
  "github.com/gobuffalo/packr/packr"
]

ignored = [
  "github.com/WillAbides/xqsmee/script/*",
]

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"
