#!/bin/sh

set -e
ROOTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$ROOTPATH"

GOBIN="$ROOTPATH/bin" go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint/

bin/golangci-lint run $@
