// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queue.proto

/*
Package queue is a generated protocol buffer package.

It is generated from these files:
	queue.proto

It has these top-level messages:
	Header
	WebRequest
	PopRequest
	PopResponse
	BPopRequest
	BPopResponse
	PeekRequest
	PeekResponse
	PushRequest
	PushResponse
*/
package queue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Name  string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Header) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type WebRequest struct {
	ReceivedAt int64     `protobuf:"varint,1,opt,name=ReceivedAt" json:"ReceivedAt,omitempty"`
	Header     []*Header `protobuf:"bytes,2,rep,name=Header" json:"Header,omitempty"`
	Host       string    `protobuf:"bytes,3,opt,name=Host" json:"Host,omitempty"`
	Body       string    `protobuf:"bytes,4,opt,name=Body" json:"Body,omitempty"`
}

func (m *WebRequest) Reset()                    { *m = WebRequest{} }
func (m *WebRequest) String() string            { return proto.CompactTextString(m) }
func (*WebRequest) ProtoMessage()               {}
func (*WebRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WebRequest) GetReceivedAt() int64 {
	if m != nil {
		return m.ReceivedAt
	}
	return 0
}

func (m *WebRequest) GetHeader() []*Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *WebRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *WebRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type PopRequest struct {
	QueueName string `protobuf:"bytes,1,opt,name=QueueName" json:"QueueName,omitempty"`
}

func (m *PopRequest) Reset()                    { *m = PopRequest{} }
func (m *PopRequest) String() string            { return proto.CompactTextString(m) }
func (*PopRequest) ProtoMessage()               {}
func (*PopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PopRequest) GetQueueName() string {
	if m != nil {
		return m.QueueName
	}
	return ""
}

type PopResponse struct {
	WebRequest *WebRequest `protobuf:"bytes,1,opt,name=WebRequest" json:"WebRequest,omitempty"`
}

func (m *PopResponse) Reset()                    { *m = PopResponse{} }
func (m *PopResponse) String() string            { return proto.CompactTextString(m) }
func (*PopResponse) ProtoMessage()               {}
func (*PopResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PopResponse) GetWebRequest() *WebRequest {
	if m != nil {
		return m.WebRequest
	}
	return nil
}

type BPopRequest struct {
	QueueName string `protobuf:"bytes,1,opt,name=QueueName" json:"QueueName,omitempty"`
	Timeout   int64  `protobuf:"varint,2,opt,name=Timeout" json:"Timeout,omitempty"`
}

func (m *BPopRequest) Reset()                    { *m = BPopRequest{} }
func (m *BPopRequest) String() string            { return proto.CompactTextString(m) }
func (*BPopRequest) ProtoMessage()               {}
func (*BPopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BPopRequest) GetQueueName() string {
	if m != nil {
		return m.QueueName
	}
	return ""
}

func (m *BPopRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type BPopResponse struct {
	WebRequest *WebRequest `protobuf:"bytes,1,opt,name=WebRequest" json:"WebRequest,omitempty"`
}

func (m *BPopResponse) Reset()                    { *m = BPopResponse{} }
func (m *BPopResponse) String() string            { return proto.CompactTextString(m) }
func (*BPopResponse) ProtoMessage()               {}
func (*BPopResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BPopResponse) GetWebRequest() *WebRequest {
	if m != nil {
		return m.WebRequest
	}
	return nil
}

type PeekRequest struct {
	QueueName string `protobuf:"bytes,1,opt,name=QueueName" json:"QueueName,omitempty"`
	Count     int64  `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
}

func (m *PeekRequest) Reset()                    { *m = PeekRequest{} }
func (m *PeekRequest) String() string            { return proto.CompactTextString(m) }
func (*PeekRequest) ProtoMessage()               {}
func (*PeekRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PeekRequest) GetQueueName() string {
	if m != nil {
		return m.QueueName
	}
	return ""
}

func (m *PeekRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PeekResponse struct {
	WebRequest []*WebRequest `protobuf:"bytes,1,rep,name=WebRequest" json:"WebRequest,omitempty"`
}

func (m *PeekResponse) Reset()                    { *m = PeekResponse{} }
func (m *PeekResponse) String() string            { return proto.CompactTextString(m) }
func (*PeekResponse) ProtoMessage()               {}
func (*PeekResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PeekResponse) GetWebRequest() []*WebRequest {
	if m != nil {
		return m.WebRequest
	}
	return nil
}

type PushRequest struct {
	QueueName  string        `protobuf:"bytes,1,opt,name=QueueName" json:"QueueName,omitempty"`
	WebRequest []*WebRequest `protobuf:"bytes,2,rep,name=WebRequest" json:"WebRequest,omitempty"`
}

func (m *PushRequest) Reset()                    { *m = PushRequest{} }
func (m *PushRequest) String() string            { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()               {}
func (*PushRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PushRequest) GetQueueName() string {
	if m != nil {
		return m.QueueName
	}
	return ""
}

func (m *PushRequest) GetWebRequest() []*WebRequest {
	if m != nil {
		return m.WebRequest
	}
	return nil
}

type PushResponse struct {
}

func (m *PushResponse) Reset()                    { *m = PushResponse{} }
func (m *PushResponse) String() string            { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()               {}
func (*PushResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*Header)(nil), "Header")
	proto.RegisterType((*WebRequest)(nil), "WebRequest")
	proto.RegisterType((*PopRequest)(nil), "PopRequest")
	proto.RegisterType((*PopResponse)(nil), "PopResponse")
	proto.RegisterType((*BPopRequest)(nil), "BPopRequest")
	proto.RegisterType((*BPopResponse)(nil), "BPopResponse")
	proto.RegisterType((*PeekRequest)(nil), "PeekRequest")
	proto.RegisterType((*PeekResponse)(nil), "PeekResponse")
	proto.RegisterType((*PushRequest)(nil), "PushRequest")
	proto.RegisterType((*PushResponse)(nil), "PushResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Queue service

type QueueClient interface {
	Pop(ctx context.Context, in *PopRequest, opts ...grpc.CallOption) (*PopResponse, error)
	BPop(ctx context.Context, in *BPopRequest, opts ...grpc.CallOption) (*BPopResponse, error)
	Peek(ctx context.Context, in *PeekRequest, opts ...grpc.CallOption) (*PeekResponse, error)
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
}

type queueClient struct {
	cc *grpc.ClientConn
}

func NewQueueClient(cc *grpc.ClientConn) QueueClient {
	return &queueClient{cc}
}

func (c *queueClient) Pop(ctx context.Context, in *PopRequest, opts ...grpc.CallOption) (*PopResponse, error) {
	out := new(PopResponse)
	err := grpc.Invoke(ctx, "/Queue/Pop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) BPop(ctx context.Context, in *BPopRequest, opts ...grpc.CallOption) (*BPopResponse, error) {
	out := new(BPopResponse)
	err := grpc.Invoke(ctx, "/Queue/BPop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) Peek(ctx context.Context, in *PeekRequest, opts ...grpc.CallOption) (*PeekResponse, error) {
	out := new(PeekResponse)
	err := grpc.Invoke(ctx, "/Queue/Peek", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := grpc.Invoke(ctx, "/Queue/Push", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Queue service

type QueueServer interface {
	Pop(context.Context, *PopRequest) (*PopResponse, error)
	BPop(context.Context, *BPopRequest) (*BPopResponse, error)
	Peek(context.Context, *PeekRequest) (*PeekResponse, error)
	Push(context.Context, *PushRequest) (*PushResponse, error)
}

func RegisterQueueServer(s *grpc.Server, srv QueueServer) {
	s.RegisterService(&_Queue_serviceDesc, srv)
}

func _Queue_Pop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).Pop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/Pop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).Pop(ctx, req.(*PopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_BPop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BPopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).BPop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/BPop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).BPop(ctx, req.(*BPopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_Peek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).Peek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/Peek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).Peek(ctx, req.(*PeekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Queue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Queue",
	HandlerType: (*QueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pop",
			Handler:    _Queue_Pop_Handler,
		},
		{
			MethodName: "BPop",
			Handler:    _Queue_BPop_Handler,
		},
		{
			MethodName: "Peek",
			Handler:    _Queue_Peek_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _Queue_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "queue.proto",
}

func init() { proto.RegisterFile("queue.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0xa4, 0x4d, 0x3f, 0xe8, 0xdb, 0xd4, 0xc3, 0xd2, 0xc3, 0x52, 0x44, 0xcb, 0x7a, 0x29, 0x0a,
	0x7b, 0x88, 0x37, 0x3d, 0x35, 0x22, 0xf4, 0x24, 0x71, 0x11, 0xf4, 0xda, 0xda, 0x07, 0x2d, 0xda,
	0x6c, 0xda, 0xcd, 0x16, 0xfc, 0x27, 0xfe, 0x5c, 0xd9, 0x5d, 0x42, 0xb6, 0x82, 0x25, 0x78, 0x7b,
	0x6f, 0x32, 0x99, 0x99, 0x37, 0x21, 0x40, 0x76, 0x06, 0x0d, 0x8a, 0x62, 0xaf, 0x4a, 0xc5, 0x13,
	0xe8, 0xcd, 0x71, 0xb1, 0xc2, 0x3d, 0xa5, 0xd0, 0xc9, 0x17, 0x5b, 0x64, 0xad, 0x49, 0x6b, 0x3a,
	0x90, 0x6e, 0xa6, 0x23, 0xe8, 0x1e, 0x16, 0x9f, 0x06, 0x59, 0x7b, 0x12, 0x4d, 0x07, 0xd2, 0x2f,
	0xdc, 0x00, 0xbc, 0xe2, 0x52, 0xe2, 0xce, 0xa0, 0x2e, 0xe9, 0x05, 0x80, 0xc4, 0x77, 0xdc, 0x1c,
	0x70, 0x35, 0x2b, 0xdd, 0xdb, 0x91, 0x0c, 0x10, 0x7a, 0x59, 0x39, 0x38, 0x11, 0x92, 0xf4, 0x85,
	0x5f, 0x65, 0x60, 0x3c, 0x57, 0xba, 0x64, 0x91, 0x37, 0xb6, 0xb3, 0xc5, 0x52, 0xb5, 0xfa, 0x62,
	0x1d, 0x8f, 0xd9, 0x99, 0x5f, 0x03, 0x64, 0xaa, 0xa8, 0x6c, 0xcf, 0x61, 0xf0, 0x6c, 0xef, 0x78,
	0xaa, 0x33, 0xd7, 0x00, 0xbf, 0x03, 0xe2, 0xb8, 0xba, 0x50, 0xb9, 0x46, 0x7a, 0x13, 0x26, 0x76,
	0x6c, 0x92, 0x10, 0x51, 0x43, 0x32, 0x78, 0xcc, 0x1f, 0x81, 0xa4, 0x4d, 0x8d, 0x28, 0x83, 0xfe,
	0xcb, 0x66, 0x8b, 0xca, 0x94, 0xac, 0xed, 0x4e, 0xaf, 0x56, 0x7e, 0x0f, 0x71, 0xfa, 0xef, 0x0c,
	0x33, 0x20, 0x19, 0xe2, 0x47, 0xb3, 0x0c, 0x23, 0xe8, 0x3e, 0x28, 0x93, 0x57, 0x09, 0xfc, 0x62,
	0xfd, 0xbd, 0xc4, 0x1f, 0xfe, 0xd1, 0x29, 0xff, 0x37, 0x20, 0x99, 0xd1, 0xeb, 0x66, 0xfe, 0xc7,
	0xca, 0xed, 0xd3, 0xca, 0x67, 0x10, 0x7b, 0x65, 0x1f, 0x2b, 0xf9, 0x6e, 0x41, 0xd7, 0x49, 0xd1,
	0x09, 0x44, 0x99, 0x2a, 0x28, 0x11, 0x75, 0xf9, 0xe3, 0x58, 0x84, 0x15, 0x5e, 0x41, 0xc7, 0x56,
	0x4a, 0x63, 0x11, 0x7c, 0xa0, 0xf1, 0x50, 0xa4, 0xbf, 0x48, 0xf6, 0x6e, 0x1a, 0x8b, 0xa0, 0xc1,
	0xf1, 0x50, 0x1c, 0x95, 0x61, 0x49, 0x46, 0xaf, 0x2d, 0xa9, 0x3e, 0xd3, 0x92, 0x82, 0x68, 0xcb,
	0x9e, 0xfb, 0x45, 0x6e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xf4, 0x5c, 0x6b, 0x31, 0x03,
	0x00, 0x00,
}
